server:
    port: 8000
    error:
        include-message: always
        include-binding-errors: always
rednet:
    app:
        api-token-cookie-name: rednet-api-access
        api-token-cookie-path: /api
        api-token-cookie-expiration-s: 120
        api-token-expiration-ms: 1800000
        api-token-issuer: rednet-agw
        api-token-secret-key: ${API_TOKEN_SECRET_KEY}
        auth-token-cookie-name: rednet-auth-access
        auth-token-cookie-path: /
        auth-token-cookie-expiration-s: 120
        auth-token-expiration-ms: 1800000
        auth-token-issuer: rednet-auth
        auth-token-secret-key: ${AUTH_TOKEN_SECRET_KEY}
