server:
    port: 8000
    error:
        include-message: always
        include-binding-errors: always
rednet:
    app:
        api-token-cookie-name: rednet-api-token
        api-token-expiration-ms: 1800000
        api-token-issuer: rednet-agw
        api-token-secret-key: ${API_TOKEN_SECRET_KEY}
        access-token-cookie-name: rednet-access-token
        access-token-secret-key: ${AUTH_TOKEN_SECRET_KEY}
        auth-token-issuer: rednet-auth
